# Generated by Django 5.0.1 on 2024-05-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('bCreateDate', models.DateTimeField(auto_now_add=True)),
                ('coverImg', models.URLField(max_length=512)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedAt', models.DateTimeField(auto_now_add=True)),
                ('diff', models.IntegerField(default=0)),
                ('writer', models.CharField(max_length=30, null=True)),
                ('genre', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'draft',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowerName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flower',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('profImg', models.URLField(max_length=512)),
                ('seedCnt', models.IntegerField(default=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('createCnt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introMode', models.BooleanField()),
                ('subject', models.CharField(max_length=100)),
                ('IntroContent', models.TextField(null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'intro',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'follower',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedCap', models.CharField(max_length=512)),
                ('feedContent', models.TextField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='DraftPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageNum', models.IntegerField()),
                ('pageContent', models.TextField()),
                ('pageImage', models.URLField(max_length=512, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'draftpage',
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members'),
        ),
        migrations.CreateModel(
            name='MyFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getDate', models.DateField()),
                ('isActive', models.BooleanField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.flower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'myflower',
            },
        ),
        migrations.CreateModel(
            name='MyForest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'myforest',
            },
        ),
        migrations.CreateModel(
            name='MyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusback.members')),
            ],
            options={
                'db_table': 'mylibrary',
            },
        ),
    ]
