# Generated by Django 5.0.1 on 2024-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('title_image_url', models.URLField(max_length=1024)),
            ],
            options={
                'db_table': 'titleimage',
            },
        ),
    ]
