# Generated by Django 5.1.2 on 2024-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0003_titleimage_img_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookShortStory',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='draft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='coverImg',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='profImg',
            field=models.URLField(default='https://i.pinimg.com/564x/f3/d1/ed/f3d1edf10d63c40e1fa06364176fa502.jpg', max_length=512),
        ),
    ]